Transform: 'AWS::Serverless-2016-10-31'
Resources:
  UserAuth:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      Handler: src/index.handler
      Timeout: 12
      MemorySize: 256
